# Uncomment this line to define a global platform for your project
platform :ios, '15.5'

# CocoaPods platforms must be compatible with the org.cocoapods.platform property in the Flutter framework.
# for more information, see https://github.com/flutter/flutter/wiki/CocoaPods-platform-support

# Prevent CocoaPods from searching for a default target.
# For more information, see https://github.com/CocoaPods/CocoaPods/issues/3289
flutter_ios_podfile_setup = File.join(File.dirname(File.expand_path(__FILE__)), 'Flutter', 'flutter_export_environment.sh')
if File.exist?(flutter_ios_podfile_setup)
  load File.join(File.dirname(File.expand_path(__FILE__)), 'Flutter', 'podhelper.rb')
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.expand_path(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.5'
    end
  end
end
